Class IRISDemo.BO.PMML.ExecuteModelResp Extends (%Persistent,Ens.Response)
{
	Property ModelOutput As Array of %String;
	
Storage Default
{
<Data name="ExecuteModelRespDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>ModelOutput</Value>
</Value>
</Data>
<DataLocation>^IRISDemo.B117E.ExecuteModeD93DD</DataLocation>
<DefaultData>ExecuteModelRespDefaultData</DefaultData>
<IdLocation>^IRISDemo.B117E.ExecuteModeD93DD</IdLocation>
<IndexLocation>^IRISDemo.B117E.ExecuteModeD93DI</IndexLocation>
<StreamLocation>^IRISDemo.B117E.ExecuteModeD93DS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}